Add XMPP WebSocket / Stream Management support

diff --git a/web/rootfs/etc/cont-init.d/10-config b/web/rootfs/etc/cont-init.d/10-config
--- a/web/rootfs/etc/cont-init.d/10-config
+++ b/web/rootfs/etc/cont-init.d/10-config
@@ -85,6 +85,17 @@ if [[ ! -f /config/config.js ]]; then
         /config/config.js
     fi
 
+    if [[ $ENABLE_XMPP_WEBSOCKET -eq 1 ]]; then
+        if [[ -z "$PUBLIC_URL" ]]; then
+            echo 'FATAL ERROR: If ENABLE_XMPP_WEBSOCKET is set to 1, PUBLIC_URL must be defined!'
+            exit 1
+        fi
+
+        sed -i \
+          -e "s#// websocket:.*#websocket: '${PUBLIC_URL/http/ws}/xmpp-websocket',#" \
+        /config/config.js
+    fi
+
     if [[ $ENABLE_AUTH -eq 1 ]]; then
         if [[ $ENABLE_GUESTS -eq 1 ]]; then
             sed -i \
